"""phase 1 core schema

Revision ID: 5b5041ef8a34
Revises: 
Create Date: 2026-09-19 23:06:27.152071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5041ef8a34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('niche', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('voice', sa.String(length=120), nullable=True),
    sa.Column('template', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=120), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_component'), 'system_logs', ['component'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_job_id'), 'system_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_table('ideas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('provisional_title', sa.String(length=255), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('angle', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=255), nullable=True),
    sa.Column('retention_potential', sa.Float(), nullable=True),
    sa.Column('suggested_sources', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('source_facts', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideas_channel_id'), 'ideas', ['channel_id'], unique=False)
    op.create_table('learning_insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('insight_type', sa.String(length=120), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_insights_channel_id'), 'learning_insights', ['channel_id'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('auth_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_accounts_channel_id'), 'platform_accounts', ['channel_id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idea_id', sa.String(length=36), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_idea_id'), 'scripts', ['idea_id'], unique=True)
    op.create_table('script_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('narrative_structure', sa.Text(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('on_screen_text', sa.JSON(), nullable=False),
    sa.Column('visual_keywords', sa.JSON(), nullable=False),
    sa.Column('image_suggestions', sa.JSON(), nullable=False),
    sa.Column('video_suggestions', sa.JSON(), nullable=False),
    sa.Column('effects_suggested', sa.JSON(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('scenes_json', sa.JSON(), nullable=False),
    sa.Column('duration_target_seconds', sa.Integer(), nullable=False),
    sa.Column('corrections_applied', sa.JSON(), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id', 'version', name='uq_script_version')
    )
    op.create_index(op.f('ix_script_versions_script_id'), 'script_versions', ['script_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_script_id'), 'videos', ['script_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('idea_id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=True),
    sa.Column('video_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('script_revision_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=120), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_channel_id'), 'jobs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_jobs_idea_id'), 'jobs', ['idea_id'], unique=False)
    op.create_index(op.f('ix_jobs_script_id'), 'jobs', ['script_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_video_id'), 'jobs', ['video_id'], unique=False)
    op.create_table('publication_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'platform', 'scheduled_at', name='uq_publication_slot')
    )
    op.create_index(op.f('ix_publication_slots_channel_id'), 'publication_slots', ['channel_id'], unique=False)
    op.create_index(op.f('ix_publication_slots_scheduled_at'), 'publication_slots', ['scheduled_at'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'idempotency_key', name='uq_publication_idempotency')
    )
    op.create_index(op.f('ix_publications_video_id'), 'publications', ['video_id'], unique=False)
    op.create_table('video_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('render_config_json', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'version', name='uq_video_version')
    )
    op.create_index(op.f('ix_video_versions_video_id'), 'video_versions', ['video_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_job_id'), 'agent_runs', ['job_id'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_captured_at'), 'analytics', ['captured_at'], unique=False)
    op.create_index(op.f('ix_analytics_publication_id'), 'analytics', ['publication_id'], unique=False)
    op.create_table('approval_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_results_job_id'), 'approval_results', ['job_id'], unique=False)
    op.create_table('review_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('scores_json', sa.JSON(), nullable=False),
    sa.Column('issues_json', sa.JSON(), nullable=False),
    sa.Column('corrections_json', sa.JSON(), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_results_job_id'), 'review_results', ['job_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_version_id', sa.String(length=36), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('visual', sa.Text(), nullable=True),
    sa.Column('text_overlay', sa.Text(), nullable=True),
    sa.Column('effect', sa.String(length=120), nullable=True),
    sa.Column('transition', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_version_id'], ['video_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_video_version_id'), 'scenes', ['video_version_id'], unique=False)
    op.create_table('state_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=False),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_events_job_id'), 'state_events', ['job_id'], unique=False)
    op.create_table('voiceovers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_version_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('voice_name', sa.String(length=120), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_version_id'], ['video_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voiceovers_video_version_id'), 'voiceovers', ['video_version_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('license_type', sa.String(length=120), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_scene_id'), 'assets', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_scene_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_voiceovers_video_version_id'), table_name='voiceovers')
    op.drop_table('voiceovers')
    op.drop_index(op.f('ix_state_events_job_id'), table_name='state_events')
    op.drop_table('state_events')
    op.drop_index(op.f('ix_scenes_video_version_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_review_results_job_id'), table_name='review_results')
    op.drop_table('review_results')
    op.drop_index(op.f('ix_approval_results_job_id'), table_name='approval_results')
    op.drop_table('approval_results')
    op.drop_index(op.f('ix_analytics_publication_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_captured_at'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_agent_runs_job_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_video_versions_video_id'), table_name='video_versions')
    op.drop_table('video_versions')
    op.drop_index(op.f('ix_publications_video_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_publication_slots_scheduled_at'), table_name='publication_slots')
    op.drop_index(op.f('ix_publication_slots_channel_id'), table_name='publication_slots')
    op.drop_table('publication_slots')
    op.drop_index(op.f('ix_jobs_video_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_script_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idea_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_channel_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_videos_script_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_script_versions_script_id'), table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index(op.f('ix_scripts_idea_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_platform_accounts_channel_id'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_learning_insights_channel_id'), table_name='learning_insights')
    op.drop_table('learning_insights')
    op.drop_index(op.f('ix_ideas_channel_id'), table_name='ideas')
    op.drop_table('ideas')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_job_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_component'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('settings')
    op.drop_table('channels')
    op.drop_table('agents')
    # ### end Alembic commands ###
